### ISSUE TITLE
Tile Command

### ISSUE THREAD

**Issue by Cybranrules** [anneheijink/spectrangle-protocol#2]
when sending a tile upsidedown, instead of keeping the rotation counterclockwise change it to it's mirror,
this will cause the left neighbour of RBG0 to always be G (no matter if upsidedown or not)
this will cause the right neighbour of RBG0 to always be B (no matter if upsidedown or not)
this will cause the top/ bot neighbour of RBG0 to always be R (no matter if upsidedown or not)

for rotation you can then use; <string>.charAt(<<see below>>)
   -   top/bot: (0 + rotation) % 3
   -   right: (1 + rotation) % 3
   -   left: (2 + rotation) % 3

this is 100000% way more efficient when coding

**Comment by anneheijink** [comment]
That sounds like a good idea, thanks for your input! However, in this way your RGB0 tile suddenly becomes an RBG0 tile. It is not the same tile anymore.

In the way it's defined now, it's also easy to compare tile. A neighboring tile is always flipped compared to the tile you're about to place. This means that, when no tile is rotated, you can compare the same index numbers with each other.
