### ISSUE TITLE
SERVERMESSAGE

### ISSUE THREAD

**Issue by Cybranrules** [anneheijink/spectrangle-protocol#4]
when something happens that is interesting to all players connected to the server like:

SERVERMESSAGE : <player> has joined

or 

SERVERMESSAGE : <player> [player] ... are waiting for a game

**Comment by anneheijink** [comment]
You can already see which players have entered the lobby. Each time a player enters / leaves a lobby, the server has to send a new LOBBY command containing all players currently in the lobby.
